on: [push]

jobs:
  mypy:
    runs-on: ubuntu-latest
    name: "mypy"
    steps:
      - uses: davidslusser/actions_python_mypy@v1.0.1
        with:
          src: "src"
          options: ""
          pip_install_command: "pip install -e .[dev]"
          python_version: "3.11"
